theme:
  version: '1.0'
  items:
    - timestamp
    - level
    - logger
    - message
    - fields
    - caller
  formatting:
    timestamp:
      outer:
        style:
          modes: [faint]
    level:
      all:
        outer:
          prefix: '|'
          suffix: '|'
      debug:
        text: 'DBG'
        inner:
          style:
            foreground: magenta
      info:
        text: 'INF'
        inner:
          style:
            foreground: cyan
      warning:
        text: 'WRN'
        outer:
          style:
            foreground: yellow
            modes: [reversed]
      error:
        text: 'ERR'
        outer:
          style:
            foreground: bright-red
            modes: [reversed]
      unknown:
        text: '(?)'
        inner:
          style:
            foreground: default
    logger:
      outer:
        suffix: ':'
        style:
          modes: [faint]
    message:
      inner:
        style:
          modes: [bold]
    field:
      inner:
        style:
          modes: [faint]
      separator: '='
    key:
      outer:
        style:
          foreground: green
    caller:
      outer:
        prefix: '@ '
        style:
          modes: [italic,faint]
    types:
      array:
        outer:
          prefix: '['
          suffix: ']'
        inner:
          prefix: ''
          suffix: ''
        separator: ','
      object:
        outer:
          prefix: '{'
          suffix: '}'
        inner:
          prefix: ' '
          suffix: ' '
        separator: ' '
      string:
        outer:
          prefix: ''''
          suffix: ''''
          style:
            modes: [faint]
        inner:
          style:
            modes: []
      number:
        outer:
          style:
            foreground: bright-blue
      time:
        outer:
          prefix: ''''
          suffix: ''''
          style:
            foreground: bright-cyan
      duration:
        outer:
          style:
            foreground: bright-blue
      boolean:
        outer:
          style:
            foreground: yellow
      'null':
        outer:
          style:
            foreground: bright-red
      error:
        outer:
          prefix: '{'
          suffix: '}'
          style:
            foreground: default
            modes: [bold]
        inner:
          prefix: ' '
          suffix: ' '
          style:
            foreground: red
